steps:

- bash:
    # using an input-macro:
    echo "this works: $(secretvalue)"

    echo "this dosen't work: $SECRETVALUE"
    echo "this works: $MY_MAPPED_ENV_VAR" 

env:
  $MY_MAPPED_ENV_VAR: $(secretvalue)