# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo hello, world
  displayName: 'run a single line'

- script: 
     echo add other
     echo see
  displayName: 'run multi line'