pool:
  vmImage: 'ubuntu-latest'

variables:
  tier: web
  target: dev

steps:
- bash:
    echo $(tier)
    echo $(target)

  displayName: 'regular variable'

- bash:
    echo $(TIER)
    echo $(TARGET)
  displayName: 'environment variable'
