# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
- template: variables.yml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: login
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(repo)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: CopyFiles@2
      inputs:
        Contents: '**'
        TargetFolder: 'Build.ArtifactStagingDirectory'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: CI
  displayName: CI STAGE
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: echo this is a build job
      displayName: 'build project'

- stage: CD
  displayName: CD STAGE
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: new-environment
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo this is a deployment job
             displayName: 'deploy project'
